version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: weather-postgres-1
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: weather
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-airflow-1
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@weather-postgres-1:5432/weather
    volumes:
      - ./opt/airflow/dags:/opt/airflow/dags
      - "D:/Learning/DE/Weather/Sub_Data:/opt/airflow/dags/Sub_Data"      

    ports:
      - "8080:8080"
    restart: unless-stopped
    command: ["bash", "-c", "airflow db init && airflow scheduler & airflow webserver"]